version: "3"

services:
  music-ai-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - /node_modules
    ports:
      - "3000:3000"
    environment:
       - CHOKIDAR_USEPOLLING=true